"""
Email Service
Sends emails via Gmail API using shared Google OAuth (no password needed)
"""

import base64
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any, Dict, List

import httpx

from integrations.google_auth import get_access_token, refresh_tokens

logger = logging.getLogger(__name__)

GMAIL_SEND_URL = "https://gmail.googleapis.com/gmail/v1/users/me/messages/send"


class EmailService:
    """Email service using Gmail API with shared Google OAuth"""

    async def _send(self, to: str, subject: str, html_body: str) -> bool:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["To"] = to
        msg.attach(MIMEText(html_body, "html"))

        raw = base64.urlsafe_b64encode(msg.as_bytes()).decode()

        token = get_access_token()
        if not token:
            logger.error("Not authenticated with Google — cannot send email")
            return False

        headers = {"Authorization": f"Bearer {token}"}

        async with httpx.AsyncClient() as client:
            response = await client.post(GMAIL_SEND_URL, json={"raw": raw}, headers=headers)
            if response.status_code == 401:
                await refresh_tokens()
                headers = {"Authorization": f"Bearer {get_access_token()}"}
                response = await client.post(GMAIL_SEND_URL, json={"raw": raw}, headers=headers)
            if response.is_success:
                logger.info(f"Email sent to {to}")
                return True
            logger.error(f"Gmail API error {response.status_code}: {response.text}")
            return False

    async def send_daily_report(self, recipient: str, report_data: Dict[str, Any]) -> bool:
        sales = report_data.get("sales", {})
        traffic = report_data.get("traffic", {})
        inventory = report_data.get("inventory", {})

        html = f"""
        <html><body style="font-family: Arial, sans-serif;">
            <h2>Daily Performance Report</h2>
            <h3>Sales</h3>
            <ul>
                <li>Orders: {sales.get('total_orders', 0)}</li>
                <li>Revenue: ${sales.get('total_revenue', 0):.2f}</li>
                <li>AOV: ${sales.get('average_order_value', 0):.2f}</li>
            </ul>
            <h3>Traffic</h3>
            <ul>
                <li>Active Users: {traffic.get('active_users', 0)}</li>
                <li>Sessions: {traffic.get('sessions', 0)}</li>
                <li>Page Views: {traffic.get('page_views', 0)}</li>
                <li>Bounce Rate: {traffic.get('bounce_rate', 0):.2f}%</li>
            </ul>
            <h3>Inventory</h3>
            <ul>
                <li>Low Stock Items: {inventory.get('low_stock_items', 0)}</li>
            </ul>
            <p style="font-size:12px;color:#666;">Generated by Shopify Brain</p>
        </body></html>
        """
        return await self._send(recipient, "Daily Performance Report", html)

    async def send_inventory_alert(self, recipient: str, low_stock_items: List[Dict]) -> bool:
        rows = "".join(
            f"<tr><td style='padding:8px'>{i.get('product_name','N/A')}</td>"
            f"<td style='padding:8px'>{i.get('available',0)} units</td></tr>"
            for i in low_stock_items[:10]
        ) or "<tr><td colspan='2'>No low stock items</td></tr>"

        html = f"""
        <html><body style="font-family: Arial, sans-serif;">
            <h2>Inventory Alert — Low Stock</h2>
            <table border="1" cellspacing="0" style="border-collapse:collapse">
                <tr style="background:#f2f2f2"><th style="padding:8px">Product</th><th style="padding:8px">Available</th></tr>
                {rows}
            </table>
            <p style="font-size:12px;color:#666;">Generated by Shopify Brain</p>
        </body></html>
        """
        return await self._send(recipient, "Inventory Alert — Low Stock Items", html)

    async def send_seo_report(self, recipient: str, seo_findings: Dict[str, Any]) -> bool:
        metrics = seo_findings.get("audit_metrics", {})
        recs = seo_findings.get("recommendations", [])
        recs_html = "".join(
            f"<li><strong>{r.get('recommendation')}</strong> — {r.get('reason','')}</li>"
            for r in recs[:5]
        )
        html = f"""
        <html><body style="font-family: Arial, sans-serif;">
            <h2>SEO Audit Report</h2>
            <ul>
                <li>Domain Rating: {metrics.get('domain_rating','N/A')}</li>
                <li>Referring Domains: {metrics.get('referring_domains',0)}</li>
                <li>Backlinks: {metrics.get('backlinks',0)}</li>
                <li>Organic Traffic: {metrics.get('organic_search_traffic',0)}</li>
            </ul>
            <h3>Recommendations</h3>
            <ul>{recs_html or '<li>None</li>'}</ul>
            <p style="font-size:12px;color:#666;">Generated by Shopify Brain</p>
        </body></html>
        """
        return await self._send(recipient, "SEO Audit Report", html)


email_service = EmailService()
